function [success,area, poly] = combinePoly(p1,p2,method)
%    COMBINEPOLY Use polyclip to combine two polygons into a single union or intersection. 
%	 Performs union or intersection, then checks to see if the result can be described with a single 
% 	 polygon. Returns both the result and the area of the result. 

%	Output Variables:
%	success - a flag stating whether the operation was successful or whether it failed.
%	area - The area of the resulting polgon
%	poly - The polygon that was generated by the operation

% 	Input Variables
%	p1 - the vertices of polygon 1, These should be in the format created by FoV_project.m
% 	p2 - the vertices of polygon 2
%	method - The method used by polyclip 'uni' for union. 'int' for intersection. 

[a,b] = polyclip(p1(:,1),p1(:,2),p2(:,1),p2(:,2),method);

if length(a) == 1
    area = polyarea(a{1},b{1});
    poly = [a{1},b{1}];
    success = 1;
else
    area = 0;
    poly = p1;
    success = 0;
end

end